version: '3.3'
services:
  app:
    image: fcoin-balances-manager
    container_name: fcoin-balances-manager
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    command: go run ./cmd/main.go
    environment:
      HTTP_PORT: 8080
      DB_HOST: db # service name of db to connect
      DB_PORT: 3306
      DB_USER: ${USERNAME} # 各環境に合わせて設定（ローカルでは.envを使う）
      DB_PASSWORD: ${USERPASS} # 各環境に合わせて設定
      DB_NAME: ${DATABASE} # 各環境に合わせて設定
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.32
    platform: linux/amd64
    container_name: fcoin-balances-db
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER} # 各環境に合わせて設定（ローカルでは.envを使う）
      MYSQL_ROOT_PASSWORD: ${ROOTPASS} # 各環境に合わせて設定（ローカルでは.envを使う）
      MYSQL_USER: ${USERNAME} # 各環境に合わせて設定（ローカルでは.envを使う）
      MYSQL_PASSWORD: ${USERPASS} # 各環境に合わせて設定（ローカルでは.envを使う）
      MYSQL_DATABASE: ${DATABASE} # 各環境に合わせて設定（ローカルでは.envを使う）
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 50s
    ports:
      - "3306:3306"
    volumes:
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
      - db_data:/var/lib/mysql
      - $PWD/_tools/mysql/init/:/docker-entrypoint-initdb.d
volumes:
  db_data:
    driver: local
