name: test
on:
  push:
    branches:
      - '**'
jobs:
  test:
    name: Run test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build And Run
        run: |
          docker compose \
            -f docker-compose.yaml \
            --env-file .env \
            up -d

      - name: Test
        run: |
          docker compose \
            -f docker-compose.yaml \
            --env-file .env \
            exec app \
            go test -v -race -shuffle=on -covermode=atomic ./...