name: test
on:
  push:
    branches:
      - '**'
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          docker compose \
            -f docker-compose.test.yaml \
            --env-file .env \
            up -d

      - name: Test
        run: |
            go test -v -race -shuffle=on -covermode=atomic ./...