name: test
on:
  push:
    branches:
      - '**'
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build And Run
        run: |
          docker compose \
            -f docker-compose.yaml \
            --env-file .env \
            up -d

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Test
        run: |
            go test -v -race -shuffle=on -covermode=atomic ./...